version: '1.0'
services:
  db:
    image: mysql
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3305:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: